import {Request} from "express";
import {v4 as uuidV4} from "uuid";
import {ProductEntity} from "../../api/entities/product.entity";

export class RequestFixture {
    static getEmptyRequest(): Request {
        return {} as unknown as Request
    }

    static getRequestWithProductIdParam(id: string): Request{
        return {
            params: {
                productId: id
            }
        } as unknown as Request
    }

    static getRequestWithProductIdParamAutoGenerated(): Request {
        return {
            params: {
                productId: uuidV4()
            }
        } as unknown as Request
    }

    static getRequestWithProductBody(name: string, price: number, categories: string[]): Request {
        return {
            body: {
                name,
                price,
                categories
            }
        } as unknown as Request
    }

    static getRequestWithProductBodyFromProductEntity(product: ProductEntity): Request {
        return {
            body: {
                name: product.name,
                price: product.price,
                categories: product.categories
            }
        } as unknown as Request
    }
}